server:
  port: 8601
  servlet:
    context-path: /regis

spring:
  application:
    name: credential-server

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/viola_credential
    username: viola
    password: 123456

# JPA properties
  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop

#Discovery server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka

#Open api documentation (swagger)
springdoc:
  swagger-ui:
    enabled: true
#to open swagger-ui go: http://localhost:8601/regis/swagger-ui/index.html


