server:
  port: 8602
  servlet:
    context-path: /user

spring:
  application:
    name: user-server

# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/viola_auth
    username: viola
    password: 123456
# JPA properties
  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop


#Discovery server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka/
      fetchRegistry: true

#Open api documentation (swagger)
springdoc:
  swagger-ui:
    enabled: true
#to open swagger-ui go: http://localhost:8602/user/swagger-ui/index.html

