server:
  port: 8603
  servlet:
    context-path: /composing

spring:
  application:
    name: composing-server

# Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demodatabase;MODE=PostgreSQL
    username: sa
    password:

# JPA properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

#Discovery server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8600/eureka/
      fetchRegistry: true

#Open api documentation (swagger)
springdoc:
  swagger-ui:
    enabled: true
#to open swagger-ui go: http://localhost:8603/composing/swagger-ui/index.html





